[workspace]
# Manual releases only - don't release on every commit
release_always = false

# Allow dirty working directories (for CI)
allow_dirty = false

# Enable git operations
git_release_enable = true
git_tag_enable = true

# Enable publishing to crates.io
publish = true

# Changelog updates
changelog_update = true

# Semver check
semver_check = true

# IMPORTANT: Features always increment minor version in 0.x releases
# This prevents features from bumping 0.x to 1.0
features_always_increment_minor = true

# Optional: Only release on certain commit types
# This filters which commits can trigger a release
# Uncomment to be more selective:
# release_commits = "^(fix|feat|perf|docs):"

[[package]]
name = "syncable-cli"

# This package should be released
release = true

# Use semantic versioning checks
semver_check = true

# Publish this package
publish = true

# Override at package level to ensure features don't bump major
features_always_increment_minor = true

# Version constraints - stay in 0.x.x range
# Note: version_max might not be supported in this version
# We'll handle version constraints manually

[changelog]
# Changelog will be updated
# Using default configuration which follows Keep a Changelog format

# Protect breaking changes from being ignored
protect_breaking_commits = false 