[workspace]
# Git configuration
git_release_enable = true
git_tag_enable = true
publish = true

# Release behavior - Manual releases only
release_always = false          # Don't release if no changes
allow_dirty = false            # Require clean working directory

[changelog]
# Changelog configuration
update = true
path = "CHANGELOG.md"
# Optional: custom changelog config
# config = "cliff.toml"

[[package]]
name = "syncable-cli"

# Manual control over version bumping
# This will be overridden by workflow_dispatch inputs
release = true

# Version constraints - STAY IN 0.x.x RANGE
# Prevent automatic major version bumps to 1.0.0
version_max = "0.99.99"        # Stay below 1.0.0

# Safety checks for manual releases
semver_check = true            # Ensure semantic versioning compliance

# Version increment rules for 0.x.x development
# patch: 0.5.4 → 0.5.5 (bug fixes)
# minor: 0.5.4 → 0.6.0 (new features)
# major: DISABLED until ready for 1.0.0 