//! CD-14 — Reusable Workflow Extraction
//!
//! For multi-environment setups, extracts common deploy logic into
//! `.github/workflows/_deploy-base.yml` as a `workflow_call` reusable workflow.
//!
//! Environment-specific workflows call this base with environment-specific inputs:
//!
//! ```yaml
//! jobs:
//!   deploy:
//!     uses: ./.github/workflows/_deploy-base.yml
//!     with:
//!       environment: production
//!       image_tag: ${{ needs.build.outputs.image }}
//!     secrets: inherit
//! ```

use super::context::{CdPlatform, DeployTarget};

// ── Public API ────────────────────────────────────────────────────────────────

/// Returns the filename for the reusable workflow base file.
pub fn base_workflow_filename() -> &'static str {
    "_deploy-base.yml"
}

/// Generates the reusable `_deploy-base.yml` workflow content.
///
/// This workflow declares `workflow_call` inputs for `environment` and
/// `image_tag`, then runs the common deploy steps.
pub fn render_reusable_base(
    platform: &CdPlatform,
    target: &DeployTarget,
    project_name: &str,
) -> String {
    let mut yaml = String::new();

    // Header
    yaml.push_str(&format!(
        "# Auto-generated by sync-ctl — Reusable deploy base for {project_name}\n"
    ));
    yaml.push_str(&format!("# Platform: {platform:?} | Target: {target}\n"));
    yaml.push_str("name: _deploy-base\n\n");

    // Trigger — workflow_call only
    yaml.push_str("on:\n");
    yaml.push_str("  workflow_call:\n");
    yaml.push_str("    inputs:\n");
    yaml.push_str("      environment:\n");
    yaml.push_str("        description: 'Deployment environment'\n");
    yaml.push_str("        required: true\n");
    yaml.push_str("        type: string\n");
    yaml.push_str("      image_tag:\n");
    yaml.push_str("        description: 'Docker image tag to deploy'\n");
    yaml.push_str("        required: true\n");
    yaml.push_str("        type: string\n");

    // Permissions
    yaml.push_str("\npermissions:\n");
    match platform {
        CdPlatform::Azure | CdPlatform::Gcp => {
            yaml.push_str("  id-token: write\n");
            yaml.push_str("  contents: read\n");
        }
        CdPlatform::Hetzner => {
            yaml.push_str("  packages: write\n");
            yaml.push_str("  contents: read\n");
        }
    }

    // Job
    yaml.push_str("\njobs:\n");
    yaml.push_str("  deploy:\n");
    yaml.push_str("    runs-on: ubuntu-latest\n");
    yaml.push_str("    environment: ${{ inputs.environment }}\n");
    yaml.push_str("    steps:\n");
    yaml.push_str("      - uses: actions/checkout@v4\n\n");
    yaml.push_str(&render_base_deploy_steps(platform, target));

    yaml
}

/// Generates a caller workflow snippet that invokes the base.
///
/// One of these is emitted per environment (e.g., `deploy-staging.yml`).
pub fn render_caller_job(
    environment_name: &str,
    image_tag_expression: &str,
    needs: Option<&str>,
) -> String {
    let mut yaml = String::new();

    yaml.push_str(&format!(
        "  deploy-{environment_name}:\n"
    ));
    yaml.push_str(&format!(
        "    uses: ./.github/workflows/{}\n",
        base_workflow_filename()
    ));
    if let Some(dep) = needs {
        yaml.push_str(&format!("    needs: {dep}\n"));
    }
    yaml.push_str("    with:\n");
    yaml.push_str(&format!(
        "      environment: {environment_name}\n"
    ));
    yaml.push_str(&format!(
        "      image_tag: {image_tag_expression}\n"
    ));
    yaml.push_str("    secrets: inherit\n");

    yaml
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn render_base_deploy_steps(platform: &CdPlatform, target: &DeployTarget) -> String {
    let mut yaml = String::new();

    // Auth step placeholder
    match platform {
        CdPlatform::Azure => {
            yaml.push_str("      - name: Azure login (OIDC)\n");
            yaml.push_str("        uses: azure/login@v2\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          client-id: ${{ secrets.AZURE_CLIENT_ID }}\n");
            yaml.push_str("          tenant-id: ${{ secrets.AZURE_TENANT_ID }}\n");
            yaml.push_str("          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}\n\n");
        }
        CdPlatform::Gcp => {
            yaml.push_str("      - name: Authenticate to GCP\n");
            yaml.push_str("        uses: google-github-actions/auth@v2\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}\n");
            yaml.push_str("          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}\n\n");
        }
        CdPlatform::Hetzner => {
            yaml.push_str("      - name: Set up SSH agent\n");
            yaml.push_str("        uses: webfactory/ssh-agent@v0.9.0\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}\n\n");
        }
    }

    // Deploy step placeholder
    yaml.push_str(&format!(
        "      - name: Deploy (${{{{ inputs.environment }}}}) to {target}\n"
    ));
    yaml.push_str("        run: |\n");
    yaml.push_str("          echo \"Deploying ${{ inputs.image_tag }} to ${{ inputs.environment }}\"\n");
    yaml.push_str(&deploy_command_for_target(target));

    yaml
}

fn deploy_command_for_target(target: &DeployTarget) -> String {
    match target {
        DeployTarget::AppService => {
            "          # az webapp config container set --name $APP_NAME --image ${{ inputs.image_tag }}\n".to_string()
        }
        DeployTarget::Aks | DeployTarget::Gke | DeployTarget::HetznerK8s => {
            "          # kubectl set image deployment/$DEPLOYMENT_NAME app=${{ inputs.image_tag }}\n".to_string()
        }
        DeployTarget::ContainerApps => {
            "          # az containerapp update --name $APP_NAME --image ${{ inputs.image_tag }}\n".to_string()
        }
        DeployTarget::CloudRun => {
            "          # gcloud run deploy $SERVICE --image ${{ inputs.image_tag }}\n".to_string()
        }
        DeployTarget::Vps => {
            "          # ssh $SSH_USER@$SSH_HOST \"docker pull ${{ inputs.image_tag }} && docker compose up -d\"\n".to_string()
        }
        DeployTarget::Coolify => {
            "          # curl -X POST $COOLIFY_WEBHOOK_URL\n".to_string()
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base_filename_is_underscore_prefixed() {
        assert!(base_workflow_filename().starts_with('_'));
        assert!(base_workflow_filename().ends_with(".yml"));
    }

    #[test]
    fn base_contains_workflow_call() {
        let yaml = render_reusable_base(
            &CdPlatform::Azure,
            &DeployTarget::AppService,
            "my-app",
        );
        assert!(yaml.contains("workflow_call:"));
    }

    #[test]
    fn base_has_environment_input() {
        let yaml = render_reusable_base(
            &CdPlatform::Azure,
            &DeployTarget::AppService,
            "my-app",
        );
        assert!(yaml.contains("environment:"));
        assert!(yaml.contains("type: string"));
    }

    #[test]
    fn base_has_image_tag_input() {
        let yaml = render_reusable_base(
            &CdPlatform::Azure,
            &DeployTarget::AppService,
            "my-app",
        );
        assert!(yaml.contains("image_tag:"));
    }

    #[test]
    fn azure_base_has_oidc_permissions() {
        let yaml = render_reusable_base(
            &CdPlatform::Azure,
            &DeployTarget::AppService,
            "my-app",
        );
        assert!(yaml.contains("id-token: write"));
    }

    #[test]
    fn hetzner_base_has_packages_permission() {
        let yaml = render_reusable_base(
            &CdPlatform::Hetzner,
            &DeployTarget::Vps,
            "my-app",
        );
        assert!(yaml.contains("packages: write"));
    }

    #[test]
    fn gcp_base_has_wif_auth() {
        let yaml = render_reusable_base(
            &CdPlatform::Gcp,
            &DeployTarget::CloudRun,
            "my-app",
        );
        assert!(yaml.contains("google-github-actions/auth@v2"));
        assert!(yaml.contains("workload_identity_provider"));
    }

    #[test]
    fn caller_job_uses_base_workflow() {
        let yaml = render_caller_job("staging", "${{ needs.build.outputs.image }}", None);
        assert!(yaml.contains("uses: ./.github/workflows/_deploy-base.yml"));
    }

    #[test]
    fn caller_job_passes_environment() {
        let yaml = render_caller_job("production", "${{ env.IMAGE_TAG }}", None);
        assert!(yaml.contains("environment: production"));
    }

    #[test]
    fn caller_job_passes_image_tag() {
        let yaml = render_caller_job("staging", "${{ env.IMAGE_TAG }}", None);
        assert!(yaml.contains("image_tag: ${{ env.IMAGE_TAG }}"));
    }

    #[test]
    fn caller_job_includes_needs_when_provided() {
        let yaml =
            render_caller_job("production", "${{ env.IMAGE_TAG }}", Some("deploy-staging"));
        assert!(yaml.contains("needs: deploy-staging"));
    }

    #[test]
    fn caller_job_no_needs_when_none() {
        let yaml = render_caller_job("dev", "${{ env.IMAGE_TAG }}", None);
        assert!(!yaml.contains("needs:"));
    }

    #[test]
    fn caller_job_inherits_secrets() {
        let yaml = render_caller_job("staging", "${{ env.IMAGE_TAG }}", None);
        assert!(yaml.contains("secrets: inherit"));
    }

    #[test]
    fn base_contains_checkout() {
        let yaml = render_reusable_base(
            &CdPlatform::Azure,
            &DeployTarget::AppService,
            "my-app",
        );
        assert!(yaml.contains("actions/checkout@v4"));
    }

    #[test]
    fn base_contains_deploy_step() {
        let yaml = render_reusable_base(
            &CdPlatform::Gcp,
            &DeployTarget::CloudRun,
            "my-app",
        );
        assert!(yaml.contains("Deploy ("));
        assert!(yaml.contains("inputs.image_tag"));
    }
}
