//! CD-13 — Rollback Step & Comments
//!
//! Generates a `.syncable/scripts/rollback.sh` script and YAML comment
//! blocks for rollback instructions. The script is parameterized per
//! platform and deploy target.
//!
//! The script accepts an `IMAGE_TAG` argument and runs the platform-specific
//! rollback command.

use super::context::{CdPlatform, DeployTarget};
use super::schema::RollbackInfo;

// ── Public API ────────────────────────────────────────────────────────────────

/// Generates the contents of `.syncable/scripts/rollback.sh`.
///
/// The script is a standalone Bash script that the user can run to rollback
/// to a specific image tag. It accepts the previous image tag as `$1`.
pub fn generate_rollback_script(
    platform: &CdPlatform,
    target: &DeployTarget,
    rollback_info: &RollbackInfo,
) -> String {
    let mut script = String::new();

    script.push_str("#!/usr/bin/env bash\n");
    script.push_str("# Auto-generated by sync-ctl — Rollback script\n");
    script.push_str(&format!(
        "# Platform: {:?} | Target: {} | Strategy: {}\n",
        platform, target, rollback_info.strategy
    ));
    script.push_str("#\n");
    script.push_str("# Usage: ./rollback.sh <previous-image-tag>\n");
    script.push_str("#   e.g. ./rollback.sh ghcr.io/org/app:abc123\n");
    script.push_str("\nset -euo pipefail\n\n");

    script.push_str("PREV_TAG=\"${1:?Usage: ./rollback.sh <previous-image-tag>}\"\n\n");

    script.push_str(&format!(
        "echo \"🔄 Rolling back to $PREV_TAG (strategy: {})\"\n\n",
        rollback_info.strategy
    ));

    script.push_str(&rollback_commands(platform, target));

    script.push_str("\necho \"✅ Rollback complete\"\n");

    script
}

/// Renders the YAML comment block for rollback that goes at the end of each
/// deploy job. Enhanced version with script reference.
pub fn render_rollback_yaml_comment(
    rollback_info: &RollbackInfo,
) -> String {
    format!(
        "\
# ── Rollback ──────────────────────────────────────────────────
# Strategy: {}
# Command:  {}
#
# Automated script: .syncable/scripts/rollback.sh <previous-image-tag>
",
        rollback_info.strategy, rollback_info.command_hint
    )
}

/// Returns the relative path for the rollback script.
pub fn rollback_script_path() -> &'static str {
    ".syncable/scripts/rollback.sh"
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn rollback_commands(platform: &CdPlatform, target: &DeployTarget) -> String {
    match (platform, target) {
        (CdPlatform::Azure, DeployTarget::AppService) => {
            "\
# Azure App Service rollback
az webapp config container set \\
  --resource-group \"${RESOURCE_GROUP:?Set RESOURCE_GROUP}\" \\
  --name \"${APP_NAME:?Set APP_NAME}\" \\
  --container-image-name \"$PREV_TAG\"
"
            .to_string()
        }
        (CdPlatform::Azure, DeployTarget::Aks) => {
            "\
# AKS rollback via kubectl
kubectl rollout undo deployment/\"${DEPLOYMENT_NAME:?Set DEPLOYMENT_NAME}\" \\
  -n \"${K8S_NAMESPACE:-default}\"
# Or deploy a specific image:
# kubectl set image deployment/$DEPLOYMENT_NAME app=$PREV_TAG -n $K8S_NAMESPACE
"
            .to_string()
        }
        (CdPlatform::Azure, DeployTarget::ContainerApps) => {
            "\
# Azure Container Apps rollback
az containerapp update \\
  --name \"${APP_NAME:?Set APP_NAME}\" \\
  --resource-group \"${RESOURCE_GROUP:?Set RESOURCE_GROUP}\" \\
  --image \"$PREV_TAG\"
"
            .to_string()
        }
        (CdPlatform::Gcp, DeployTarget::CloudRun) => {
            "\
# Cloud Run rollback — shift traffic to previous revision
gcloud run services update-traffic \"${CLOUD_RUN_SERVICE:?Set CLOUD_RUN_SERVICE}\" \\
  --region=\"${GCP_REGION:?Set GCP_REGION}\" \\
  --to-revisions=LATEST=0
# Or deploy a specific image:
# gcloud run deploy $CLOUD_RUN_SERVICE --image=$PREV_TAG --region=$GCP_REGION
"
            .to_string()
        }
        (CdPlatform::Gcp, DeployTarget::Gke) => {
            "\
# GKE rollback via kubectl
kubectl rollout undo deployment/\"${DEPLOYMENT_NAME:?Set DEPLOYMENT_NAME}\" \\
  -n \"${K8S_NAMESPACE:-default}\"
"
            .to_string()
        }
        (CdPlatform::Hetzner, DeployTarget::Vps) => {
            "\
# Hetzner VPS rollback via SSH
ssh \"${SSH_USER:?Set SSH_USER}@${SSH_HOST:?Set SSH_HOST}\" << 'EOF'
  docker compose down
  docker pull \"$PREV_TAG\"
  docker compose up -d
EOF
"
            .to_string()
        }
        (CdPlatform::Hetzner, DeployTarget::HetznerK8s) => {
            "\
# Hetzner K8s rollback via kubectl
kubectl rollout undo deployment/\"${DEPLOYMENT_NAME:?Set DEPLOYMENT_NAME}\" \\
  -n \"${K8S_NAMESPACE:-default}\"
"
            .to_string()
        }
        (CdPlatform::Hetzner, DeployTarget::Coolify) => {
            "\
# Coolify rollback — trigger webhook with previous tag
curl -X POST \"${COOLIFY_WEBHOOK_URL:?Set COOLIFY_WEBHOOK_URL}\" \\
  -H 'Content-Type: application/json' \\
  -d \"{\\\"image\\\": \\\"$PREV_TAG\\\"}\"
"
            .to_string()
        }
        _ => {
            "\
# Manual rollback — redeploy the previous image tag
echo \"Redeploy $PREV_TAG using your platform's CLI or dashboard\"
"
            .to_string()
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn script_has_shebang() {
        let info = RollbackInfo {
            strategy: "redeploy-previous".to_string(),
            command_hint: "az webapp ...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Azure, &DeployTarget::AppService, &info);
        assert!(script.starts_with("#!/usr/bin/env bash"));
    }

    #[test]
    fn script_has_set_euo_pipefail() {
        let info = RollbackInfo {
            strategy: "manual".to_string(),
            command_hint: "ssh ...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Hetzner, &DeployTarget::Vps, &info);
        assert!(script.contains("set -euo pipefail"));
    }

    #[test]
    fn script_accepts_prev_tag_argument() {
        let info = RollbackInfo {
            strategy: "manual".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Azure, &DeployTarget::AppService, &info);
        assert!(script.contains("PREV_TAG=\"${1:?"));
    }

    #[test]
    fn azure_app_service_script_uses_az_webapp() {
        let info = RollbackInfo {
            strategy: "redeploy-previous".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Azure, &DeployTarget::AppService, &info);
        assert!(script.contains("az webapp config container set"));
    }

    #[test]
    fn aks_script_uses_kubectl_rollout() {
        let info = RollbackInfo {
            strategy: "rollout-undo".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Azure, &DeployTarget::Aks, &info);
        assert!(script.contains("kubectl rollout undo"));
    }

    #[test]
    fn cloud_run_script_uses_gcloud() {
        let info = RollbackInfo {
            strategy: "traffic-shift".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Gcp, &DeployTarget::CloudRun, &info);
        assert!(script.contains("gcloud run services update-traffic"));
    }

    #[test]
    fn gke_script_uses_kubectl() {
        let info = RollbackInfo {
            strategy: "rollout-undo".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Gcp, &DeployTarget::Gke, &info);
        assert!(script.contains("kubectl rollout undo"));
    }

    #[test]
    fn vps_script_uses_ssh() {
        let info = RollbackInfo {
            strategy: "manual".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Hetzner, &DeployTarget::Vps, &info);
        assert!(script.contains("ssh \"${SSH_USER"));
    }

    #[test]
    fn coolify_script_uses_webhook() {
        let info = RollbackInfo {
            strategy: "manual".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Hetzner, &DeployTarget::Coolify, &info);
        assert!(script.contains("COOLIFY_WEBHOOK_URL"));
    }

    #[test]
    fn hetzner_k8s_script_uses_kubectl() {
        let info = RollbackInfo {
            strategy: "rollout-undo".to_string(),
            command_hint: "...".to_string(),
        };
        let script =
            generate_rollback_script(&CdPlatform::Hetzner, &DeployTarget::HetznerK8s, &info);
        assert!(script.contains("kubectl rollout undo"));
    }

    #[test]
    fn yaml_comment_contains_strategy() {
        let info = RollbackInfo {
            strategy: "redeploy-previous".to_string(),
            command_hint: "az webapp ...".to_string(),
        };
        let yaml = render_rollback_yaml_comment(&info);
        assert!(yaml.contains("Strategy: redeploy-previous"));
    }

    #[test]
    fn yaml_comment_references_script() {
        let info = RollbackInfo {
            strategy: "manual".to_string(),
            command_hint: "...".to_string(),
        };
        let yaml = render_rollback_yaml_comment(&info);
        assert!(yaml.contains(".syncable/scripts/rollback.sh"));
    }

    #[test]
    fn rollback_script_path_is_correct() {
        assert_eq!(rollback_script_path(), ".syncable/scripts/rollback.sh");
    }

    #[test]
    fn container_apps_script_uses_az_containerapp() {
        let info = RollbackInfo {
            strategy: "redeploy-previous".to_string(),
            command_hint: "...".to_string(),
        };
        let script = generate_rollback_script(
            &CdPlatform::Azure,
            &DeployTarget::ContainerApps,
            &info,
        );
        assert!(script.contains("az containerapp update"));
    }
}
