//! CI-19 / DEV-43 — Secrets Inventory Generator
//!
//! Scans a rendered CI pipeline YAML for secret references, deduplicates
//! them, and formats a `SECRETS_REQUIRED.md` document that tells the user
//! exactly which repository secrets to create and how to obtain them
//! 
//! 
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::cli::{CiFormat, CiPlatform};

// ── Secret metadata ───────────────────────────────────────────────────────────

/// A single secret entry in the generated document.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecretEntry {
    pub name: String,
    pub description: String,
    pub how_to_obtain: String,
    pub where_to_set: String,
    pub required: bool,
}

impl SecretEntry {
    fn new(name: &str, description: &str, how_to_obtain: &str, where_to_set: &str, required: bool) -> Self {
        Self {
            name: name.to_string(),
            description: description.to_string(),
            how_to_obtain: how_to_obtain.to_string(),
            where_to_set: where_to_set.to_string(),
            required,
        }
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Scans `yaml` for secret references and returns a `SECRETS_REQUIRED.md`
/// document body as a `String`.
///
/// `platform` and `format` are used to emit platform-specific setup instructions
/// and to choose which regex patterns to apply.
pub fn generate_secrets_doc(yaml: &str, platform: CiPlatform, format: CiFormat) -> String {
    let names = collect_secret_names(yaml, &format);
    let entries = enrich_secrets(names, &platform);
    render_markdown(&entries, &platform)
}

/// Writes `.syncable/SECRETS_REQUIRED.md` to `output_dir`.
///
/// Creates the `.syncable/` subdirectory if it does not exist.
pub fn write_secrets_doc(
    yaml: &str,
    platform: CiPlatform,
    format: CiFormat,
    output_dir: &Path,
) -> crate::Result<()> {
    let content = generate_secrets_doc(yaml, platform, format);
    let syncable_dir = output_dir.join(".syncable");
    std::fs::create_dir_all(&syncable_dir)?;
    std::fs::write(syncable_dir.join("SECRETS_REQUIRED.md"), content)?;
    Ok(())
}

/// Produces a single `SECRETS_REQUIRED.md` covering **all** supplied platforms.
///
/// Each element of `platforms` is a `(platform, format, rendered_yaml)` triple.
/// The resulting document has one top-level `##` heading per platform so that
/// a user who generates pipelines for multiple targets (or checks this file
/// into the repository for reference) sees a complete, per-platform breakdown
/// of every secret needed.
///
/// Secrets that appear under multiple platforms are documented independently in
/// each section with platform-appropriate "where to set" instructions.
pub fn generate_secrets_doc_all_platforms(
    platforms: &[(CiPlatform, CiFormat, &str)],
) -> String {
    if platforms.is_empty() {
        return "# Secrets Required\n\nNo pipeline platforms supplied.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("# Secrets Required\n\n");
    out.push_str("Generated by `sync-ctl generate ci`.\n\n");

    let all_empty = platforms
        .iter()
        .all(|(_, fmt, yaml)| collect_secret_names(yaml, fmt).is_empty());

    if all_empty {
        out.push_str("No secrets detected in any generated pipeline.\n");
        return out;
    }

    out.push_str("---\n\n");

    for (platform, format, yaml) in platforms {
        let names = collect_secret_names(yaml, format);
        let platform_label = platform_display_label(platform);

        out.push_str(&format!("## {}\n\n", platform_label));

        if names.is_empty() {
            out.push_str("_No secrets detected for this platform._\n\n");
            continue;
        }

        let entries = enrich_secrets(names, platform);
        let required: Vec<_> = entries.iter().filter(|e| e.required).collect();
        let optional: Vec<_> = entries.iter().filter(|e| !e.required).collect();

        if !required.is_empty() {
            out.push_str("### Required\n\n");
            out.push_str(table_header());
            for e in &required { out.push_str(&table_row(e)); }
            out.push('\n');
        }
        if !optional.is_empty() {
            out.push_str("### Optional\n\n");
            out.push_str(table_header());
            for e in &optional { out.push_str(&table_row(e)); }
            out.push('\n');
        }
    }

    out
}

fn platform_display_label(platform: &CiPlatform) -> &'static str {
    match platform {
        CiPlatform::Azure => "Azure Pipelines",
        CiPlatform::Gcp => "GCP Cloud Build",
        CiPlatform::Hetzner => "Hetzner / GitHub Actions",
    }
}

/// Returns just the deduplicated set of secret names found in `yaml`.
/// Exposed for testing.
///
/// Deserializes `yaml` into a `serde_yaml::Value` tree and walks only string
/// scalar nodes, so key names, anchors, and YAML comments never produce false
/// positives.  Falls back to scanning the raw string when the YAML is not
/// parseable (e.g. a partially-rendered template with `{{PLACEHOLDER}}`
/// tokens that make the YAML invalid).
pub fn collect_secret_names(yaml: &str, format: &CiFormat) -> BTreeSet<String> {
    // Collect all string scalar values from the YAML value tree.  If the
    // document is not valid YAML (e.g. contains unquoted `{{...}}` tokens)
    // fall back to scanning the raw string directly.
    let scalars: Vec<String> = match serde_yaml::from_str::<serde_yaml::Value>(yaml) {
        Ok(root) => collect_string_scalars(&root),
        Err(_) => vec![yaml.to_string()],
    };

    let mut names = BTreeSet::new();
    for scalar in &scalars {
        scan_scalar_for_secrets(scalar, format, &mut names);
    }
    names
}

/// Recursively collects every string scalar value from a `serde_yaml::Value` tree.
fn collect_string_scalars(value: &serde_yaml::Value) -> Vec<String> {
    match value {
        serde_yaml::Value::String(s) => vec![s.clone()],
        serde_yaml::Value::Sequence(seq) => {
            seq.iter().flat_map(collect_string_scalars).collect()
        }
        serde_yaml::Value::Mapping(map) => {
            map.values().flat_map(collect_string_scalars).collect()
        }
        // Booleans, numbers, null — never contain secret references.
        _ => vec![],
    }
}

/// Applies platform-specific patterns against a single string scalar.
fn scan_scalar_for_secrets(scalar: &str, format: &CiFormat, names: &mut BTreeSet<String>) {
    use regex::Regex;

    match format {
        CiFormat::GithubActions => {
            // ${{ secrets.NAME }}
            let re = Regex::new(r"\$\{\{\s*secrets\.([A-Z0-9_]+)\s*\}\}").unwrap();
            for cap in re.captures_iter(scalar) {
                if let Some(m) = cap.get(1) { names.insert(m.as_str().to_string()); }
            }
        }
        CiFormat::AzurePipelines => {
            // $(VARIABLE_NAME) — all-caps names only (lower-case are pipeline vars, not secrets)
            let re_paren = Regex::new(r"\$\(([A-Z][A-Z0-9_]+)\)").unwrap();
            for cap in re_paren.captures_iter(scalar) {
                if let Some(m) = cap.get(1) { names.insert(m.as_str().to_string()); }
            }
            // Also catch GH-style secrets accidentally present (mixed templates)
            let re_gh = Regex::new(r"\$\{\{\s*secrets\.([A-Z0-9_]+)\s*\}\}").unwrap();
            for cap in re_gh.captures_iter(scalar) {
                if let Some(m) = cap.get(1) { names.insert(m.as_str().to_string()); }
            }
        }
        CiFormat::CloudBuild => {
            // $$_VARIABLE (double-dollar escape used in some GCP docs)
            let re_dd = Regex::new(r"\$\$([_A-Z][A-Z0-9_]*)").unwrap();
            for cap in re_dd.captures_iter(scalar) {
                if let Some(m) = cap.get(1) { names.insert(m.as_str().to_string()); }
            }
            // $_VARIABLE — standard Cloud Build user substitution
            let re_sub = Regex::new(r"\$_([A-Z][A-Z0-9_]*)").unwrap();
            for cap in re_sub.captures_iter(scalar) {
                if let Some(m) = cap.get(1) { names.insert(m.as_str().to_string()); }
            }
        }
    }
}

// ── Knowledge base ────────────────────────────────────────────────────────────

/// Builds a map of well-known secret names → `SecretEntry` metadata.
fn known_secrets() -> BTreeMap<&'static str, SecretEntry> {
    let mut m = BTreeMap::new();

    m.insert("GITHUB_TOKEN", SecretEntry::new(
        "GITHUB_TOKEN",
        "GitHub-issued token for Actions API access. Automatically available in all GitHub Actions runs.",
        "No action required — GitHub injects this automatically.",
        "Injected automatically — no manual secret needed.",
        true,
    ));
    m.insert("GITLEAKS_LICENSE", SecretEntry::new(
        "GITLEAKS_LICENSE",
        "Gitleaks commercial licence key (required for private repositories only).",
        "Purchase at https://gitleaks.io/ · Then add as a repository secret.",
        "GitHub repo → Settings → Secrets and variables → Actions → New repository secret.",
        false,
    ));
    m.insert("CODECOV_TOKEN", SecretEntry::new(
        "CODECOV_TOKEN",
        "API token for uploading coverage reports to Codecov.",
        "Sign in at https://app.codecov.io/ · Navigate to your repo · Copy the upload token.",
        "GitHub repo → Settings → Secrets and variables → Actions → New repository secret.",
        false,
    ));
    m.insert("SLACK_BOT_TOKEN", SecretEntry::new(
        "SLACK_BOT_TOKEN",
        "Slack bot OAuth token for posting CI failure notifications.",
        "Create a Slack app at https://api.slack.com/apps · Add `chat:write` scope · Install to workspace.",
        "GitHub repo → Settings → Secrets and variables → Actions → New repository secret.",
        false,
    ));
    m.insert("SLACK_CHANNEL_ID", SecretEntry::new(
        "SLACK_CHANNEL_ID",
        "Slack channel ID where CI failure notifications are posted.",
        "Right-click the channel in Slack → Copy link — the ID is the last segment (e.g. `C012AB3CD`).",
        "GitHub repo → Settings → Secrets and variables → Actions → New repository secret.",
        false,
    ));

    // Docker / container registry secrets
    for name in &["DOCKER_USERNAME", "DOCKER_PASSWORD", "DOCKER_TOKEN"] {
        m.insert(name, SecretEntry::new(
            name,
            "Docker Hub credentials for pushing container images.",
            "Create an access token at https://hub.docker.com/settings/security · Store username and token separately.",
            "GitHub repo → Settings → Secrets and variables → Actions → New repository secret.",
            true,
        ));
    }
    for name in &["ACR_LOGIN_SERVER", "ACR_USERNAME", "ACR_PASSWORD"] {
        m.insert(name, SecretEntry::new(
            name,
            "Azure Container Registry credentials.",
            "Azure Portal → Container registries → [your registry] → Access keys.",
            "Azure DevOps → Pipelines → Library **or** GitHub repo → Settings → Secrets and variables → Actions.",
            true,
        ));
    }
    for name in &["GCP_SA_KEY", "GCP_PROJECT_ID"] {
        m.insert(name, SecretEntry::new(
            name,
            "GCP service account key / project ID for pushing images to Artifact Registry.",
            "GCP Console → IAM & Admin → Service Accounts → Create key (JSON).",
            "GCP Secret Manager **or** GitHub repo → Settings → Secrets and variables → Actions.",
            true,
        ));
    }

    m
}

/// Converts a set of raw secret names into enriched `SecretEntry` values.
fn enrich_secrets(names: BTreeSet<String>, platform: &CiPlatform) -> Vec<SecretEntry> {
    let known = known_secrets();
    names
        .into_iter()
        .map(|name| {
            known.get(name.as_str()).cloned().unwrap_or_else(|| SecretEntry::new(
                &name,
                "Project-specific secret — description not yet documented.",
                "Add the value as a repository or pipeline secret.",
                &generic_where_to_set(platform),
                true,
            ))
        })
        .collect()
}

/// Returns the platform-appropriate "where to set" guidance for an unknown secret.
fn generic_where_to_set(platform: &CiPlatform) -> String {
    match platform {
        CiPlatform::Hetzner => {
            "GitHub repo → Settings → Secrets and variables → Actions → New repository secret."
                .to_string()
        }
        CiPlatform::Azure => {
            "Azure DevOps → Pipelines → Library → Variable groups → Add variable (mark as secret)."
                .to_string()
        }
        CiPlatform::Gcp => {
            "GCP Console → Secret Manager → Create secret **or** Cloud Build trigger → Substitution variables."
                .to_string()
        }
    }
}

// ── Markdown renderer ─────────────────────────────────────────────────────────

fn render_markdown(entries: &[SecretEntry], platform: &CiPlatform) -> String {
    if entries.is_empty() {
        return "# Secrets Required\n\nNo secrets detected in the generated pipeline.\n".to_string();
    }

    let platform_label = platform_display_label(platform);

    let required: Vec<_> = entries.iter().filter(|e| e.required).collect();
    let optional: Vec<_> = entries.iter().filter(|e| !e.required).collect();

    let mut out = String::new();
    out.push_str("# Secrets Required\n\n");
    out.push_str(&format!(
        "Generated by `sync-ctl generate ci` for platform **{}**.\n\n",
        platform_label
    ));
    out.push_str("---\n\n");

    if !required.is_empty() {
        out.push_str("## Required\n\n");
        out.push_str(table_header());
        for e in &required {
            out.push_str(&table_row(e));
        }
        out.push('\n');
    }

    if !optional.is_empty() {
        out.push_str("## Optional\n\n");
        out.push_str(table_header());
        for e in &optional {
            out.push_str(&table_row(e));
        }
        out.push('\n');
    }

    out
}

fn table_header() -> &'static str {
    "| Secret Name | Description | How to obtain | Where to set |\n\
     |---|---|---|---|\n"
}

fn table_row(e: &SecretEntry) -> String {
    format!(
        "| `{}` | {} | {} | {} |\n",
        e.name, e.description, e.how_to_obtain, e.where_to_set
    )
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── collect_secret_names ───────────────────────────────────────────────

    #[test]
    fn test_github_actions_secrets_extracted() {
        let yaml = r#"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OTHER: ${{ secrets.MY_TOKEN }}
"#;
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert!(names.contains("GITHUB_TOKEN"));
        assert!(names.contains("MY_TOKEN"));
    }

    #[test]
    fn test_github_actions_lowercase_secrets_ignored() {
        // Secret names in the patterns must be uppercase — lowercase vars are not secrets
        let yaml = "run: echo ${{ env.foo }}";
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert!(names.is_empty());
    }

    #[test]
    fn test_azure_dollar_paren_secrets_extracted() {
        let yaml = "value: $(ACR_PASSWORD)\nother: $(System.AccessToken)";
        let names = collect_secret_names(yaml, &CiFormat::AzurePipelines);
        assert!(names.contains("ACR_PASSWORD"));
    }

    #[test]
    fn test_cloud_build_dollar_dollar_extracted() {
        let yaml = "env:\n  - GITHUB_TOKEN=$$_GITHUB_TOKEN";
        let names = collect_secret_names(yaml, &CiFormat::CloudBuild);
        assert!(names.contains("_GITHUB_TOKEN"));
    }

    #[test]
    fn test_cloud_build_dollar_underscore_extracted() {
        let yaml = "args: [\"$_GCP_PROJECT_ID\"]";
        let names = collect_secret_names(yaml, &CiFormat::CloudBuild);
        assert!(names.contains("GCP_PROJECT_ID"));
    }

    #[test]
    fn test_deduplication() {
        let yaml = r#"
env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OTHER: ${{ secrets.GITHUB_TOKEN }}
"#;
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert_eq!(names.len(), 1);
        assert!(names.contains("GITHUB_TOKEN"));
    }

    #[test]
    fn test_empty_yaml_gives_empty_set() {
        let names = collect_secret_names("steps: []", &CiFormat::GithubActions);
        assert!(names.is_empty());
    }

    // ── enrich_secrets ─────────────────────────────────────────────────────

    #[test]
    fn test_known_secret_enriched() {
        let mut names = BTreeSet::new();
        names.insert("GITHUB_TOKEN".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Hetzner);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].name, "GITHUB_TOKEN");
        assert!(entries[0].required);
        assert!(entries[0].description.contains("GitHub-issued"));
    }

    #[test]
    fn test_unknown_secret_gets_generic_entry() {
        let mut names = BTreeSet::new();
        names.insert("MY_CUSTOM_API_KEY".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Hetzner);
        assert_eq!(entries[0].name, "MY_CUSTOM_API_KEY");
        assert!(entries[0].description.contains("Project-specific"));
    }

    #[test]
    fn test_gitleaks_license_is_optional() {
        let mut names = BTreeSet::new();
        names.insert("GITLEAKS_LICENSE".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Hetzner);
        assert!(!entries[0].required);
    }

    // ── generate_secrets_doc ───────────────────────────────────────────────

    #[test]
    fn test_doc_contains_required_heading() {
        let yaml = "env:\n  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}";
        let doc = generate_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions);
        assert!(doc.contains("## Required"));
        assert!(doc.contains("GITHUB_TOKEN"));
    }

    #[test]
    fn test_doc_contains_optional_section_for_gitleaks() {
        let yaml = r#"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GL: ${{ secrets.GITLEAKS_LICENSE }}
"#;
        let doc = generate_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions);
        assert!(doc.contains("## Optional"));
        assert!(doc.contains("GITLEAKS_LICENSE"));
    }

    #[test]
    fn test_doc_no_secrets_message() {
        let doc = generate_secrets_doc("steps: []", CiPlatform::Gcp, CiFormat::CloudBuild);
        assert!(doc.contains("No secrets detected"));
    }

    #[test]
    fn test_doc_platform_label_azure() {
        let yaml = "value: $(ACR_PASSWORD)";
        let doc = generate_secrets_doc(yaml, CiPlatform::Azure, CiFormat::AzurePipelines);
        assert!(doc.contains("Azure"));
    }

    #[test]
    fn test_doc_platform_label_gcp() {
        let yaml = "env:\n  - TOKEN=$$_GITHUB_TOKEN";
        let doc = generate_secrets_doc(yaml, CiPlatform::Gcp, CiFormat::CloudBuild);
        assert!(doc.contains("GCP"));
    }

    #[test]
    fn test_doc_is_valid_markdown_table() {
        let yaml = "env:\n  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}";
        let doc = generate_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions);
        // Table has a header row and separator row
        assert!(doc.contains("| Secret Name | Description | How to obtain |"));
        assert!(doc.contains("|---|---|---|"));
    }

    #[test]
    fn test_doc_entries_sorted_alphabetically() {
        let yaml = r#"
env:
  B: ${{ secrets.BETA_TOKEN }}
  A: ${{ secrets.ALPHA_TOKEN }}
"#;
        let doc = generate_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions);
        let alpha_pos = doc.find("ALPHA_TOKEN").unwrap();
        let beta_pos = doc.find("BETA_TOKEN").unwrap();
        assert!(alpha_pos < beta_pos, "entries should be sorted A-Z");
    }

    // ── where_to_set + write_secrets_doc ───────────────────────────────────

    #[test]
    fn test_where_to_set_field_populated_on_known_secret() {
        let mut names = BTreeSet::new();
        names.insert("GITHUB_TOKEN".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Hetzner);
        assert!(!entries[0].where_to_set.is_empty());
        assert!(entries[0].where_to_set.contains("Injected automatically"));
    }

    #[test]
    fn test_where_to_set_field_populated_on_unknown_secret() {
        let mut names = BTreeSet::new();
        names.insert("MY_CUSTOM_KEY".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Hetzner);
        assert!(entries[0].where_to_set.contains("Settings → Secrets"));
    }

    #[test]
    fn test_where_to_set_column_in_table() {
        let yaml = "env:\n  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}";
        let doc = generate_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions);
        assert!(doc.contains("| Secret Name | Description | How to obtain | Where to set |"));
        assert!(doc.contains("|---|---|---|---|"));
    }

    #[test]
    fn test_write_secrets_doc_creates_file() {
        let tmp = std::env::temp_dir().join(format!(
            "syncable_secrets_test_{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        let yaml = "env:\n  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}";
        write_secrets_doc(yaml, CiPlatform::Hetzner, CiFormat::GithubActions, &tmp).unwrap();
        let out = tmp.join(".syncable").join("SECRETS_REQUIRED.md");
        assert!(out.exists(), "SECRETS_REQUIRED.md should be created");
        let content = std::fs::read_to_string(&out).unwrap();
        assert!(content.contains("GITHUB_TOKEN"));
        assert!(content.contains("Where to set"));
        std::fs::remove_dir_all(&tmp).ok();
    }

    // ── serde_yaml scalar walker ───────────────────────────────────────────

    #[test]
    fn test_yaml_key_names_are_not_matched_as_secrets() {
        // "GITHUB_TOKEN" appears as a YAML *key*, not a value — should not be extracted.
        let yaml = "GITHUB_TOKEN: plain_string_not_a_secret_reference";
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert!(names.is_empty(), "key names must not be scanned");
    }

    #[test]
    fn test_secrets_in_nested_mapping_values_are_found() {
        let yaml = r#"
jobs:
  ci:
    env:
      TOKEN: ${{ secrets.DEEP_SECRET }}
"#;
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert!(names.contains("DEEP_SECRET"));
    }

    #[test]
    fn test_secrets_in_sequence_items_are_found() {
        let yaml = "args:\n  - \"$_MY_SECRET\"\n  - \"other\"";
        let names = collect_secret_names(yaml, &CiFormat::CloudBuild);
        assert!(names.contains("MY_SECRET"));
    }

    #[test]
    fn test_invalid_yaml_falls_back_to_raw_scan() {
        // Unquoted {{ }} makes this invalid YAML — scanner must fall back gracefully.
        let yaml = "run: deploy --token {{PLACEHOLDER}} --key ${{ secrets.FALLBACK_KEY }}";
        let names = collect_secret_names(yaml, &CiFormat::GithubActions);
        assert!(names.contains("FALLBACK_KEY"));
    }

    // ── platform-specific where_to_set ────────────────────────────────────

    #[test]
    fn test_unknown_secret_azure_gets_devops_instructions() {
        let mut names = BTreeSet::new();
        names.insert("MY_AZURE_KEY".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Azure);
        assert!(entries[0].where_to_set.contains("Azure DevOps"), 
            "Azure unknown secrets should reference Azure DevOps Library");
    }

    #[test]
    fn test_unknown_secret_gcp_gets_secret_manager_instructions() {
        let mut names = BTreeSet::new();
        names.insert("MY_GCP_KEY".to_string());
        let entries = enrich_secrets(names, &CiPlatform::Gcp);
        assert!(entries[0].where_to_set.contains("Secret Manager"),
            "GCP unknown secrets should reference Secret Manager");
    }

    // ── generate_secrets_doc_all_platforms ────────────────────────────────

    #[test]
    fn test_all_platforms_doc_has_per_platform_headings() {
        let hetzner_yaml = "env:\n  T: ${{ secrets.GITHUB_TOKEN }}";
        let azure_yaml = "value: $(ACR_PASSWORD)";
        let gcp_yaml = "args: [\"$_GCP_PROJECT_ID\"]";

        let platforms = vec![
            (CiPlatform::Hetzner, CiFormat::GithubActions, hetzner_yaml),
            (CiPlatform::Azure,   CiFormat::AzurePipelines, azure_yaml),
            (CiPlatform::Gcp,     CiFormat::CloudBuild, gcp_yaml),
        ];

        let doc = generate_secrets_doc_all_platforms(&platforms);
        assert!(doc.contains("## Hetzner / GitHub Actions"));
        assert!(doc.contains("## Azure Pipelines"));
        assert!(doc.contains("## GCP Cloud Build"));
    }

    #[test]
    fn test_all_platforms_doc_empty_platform_shows_note() {
        let platforms = vec![
            (CiPlatform::Hetzner, CiFormat::GithubActions, "steps: []"),
        ];
        let doc = generate_secrets_doc_all_platforms(&platforms);
        assert!(doc.contains("No secrets detected"));
    }

    #[test]
    fn test_all_platforms_doc_empty_input() {
        let doc = generate_secrets_doc_all_platforms(&[]);
        assert!(doc.contains("No pipeline platforms supplied"));
    }

    #[test]
    fn test_all_platforms_doc_required_optional_split() {
        let yaml = "env:\n  A: ${{ secrets.GITHUB_TOKEN }}\n  B: ${{ secrets.GITLEAKS_LICENSE }}";
        let platforms = vec![(CiPlatform::Hetzner, CiFormat::GithubActions, yaml)];
        let doc = generate_secrets_doc_all_platforms(&platforms);
        assert!(doc.contains("### Required"));
        assert!(doc.contains("### Optional"));
        assert!(doc.contains("GITHUB_TOKEN"));
        assert!(doc.contains("GITLEAKS_LICENSE"));
    }
}
