//! CD-18 — Azure CD Template Builder
//!
//! Assembles a complete `.github/workflows/deploy-azure.yml` from a
//! `CdPipeline` struct. The pipeline order is:
//!
//! 1. Checkout
//! 2. Azure login (OIDC)
//! 3. Docker build + push (via Buildx)
//! 4. Database migration *(optional)*
//! 5. Deploy to target (App Service / AKS / Container Apps)
//! 6. Health check
//!
//! All YAML is assembled by string formatting from the `CdPipeline` schema
//! types. Template builders own the full workflow structure; step modules
//! provide helpers for individual snippets at a lower level.

use crate::generator::cd_generation::{
    context::DeployTarget,
    health_check::is_kubectl_health_check,
    schema::CdPipeline,
};

/// Renders a complete Azure CD workflow YAML string.
pub fn render(pipeline: &CdPipeline) -> String {
    let mut yaml = String::with_capacity(4096);

    yaml.push_str(&render_header(pipeline));
    yaml.push_str("jobs:\n");
    yaml.push_str("  deploy:\n");
    yaml.push_str("    runs-on: ubuntu-latest\n");
    yaml.push_str("    steps:\n");

    // 1. Checkout
    yaml.push_str("      - uses: actions/checkout@v4\n\n");

    // 2. Azure login (OIDC)
    yaml.push_str(&render_auth_step(pipeline));

    // 3. Docker build + push
    yaml.push_str(&render_docker_step(pipeline));

    // 4. Migration (optional)
    if let Some(ref migration) = pipeline.migration {
        yaml.push_str(&render_migration_step(migration));
    }

    // 5. Deploy
    yaml.push_str(&render_deploy_step(pipeline));

    // 6. Health check
    yaml.push_str(&render_health_check_step(pipeline));

    // Rollback comment
    yaml.push_str(&render_rollback_comment(pipeline));

    yaml
}

/// Returns the canonical output filename.
pub fn workflow_filename() -> &'static str {
    "deploy-azure.yml"
}

// ── Private renderers ─────────────────────────────────────────────────────────

fn render_header(pipeline: &CdPipeline) -> String {
    format!(
        "\
# Auto-generated by sync-ctl — Azure CD pipeline for {project}
# Target: {target}
name: Deploy to Azure ({target})

on:
  push:
    branches:
      - {branch}
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: {image}

",
        project = pipeline.project_name,
        target = pipeline.deploy_target,
        branch = pipeline.default_branch,
        image = pipeline.image_name,
    )
}

fn render_auth_step(pipeline: &CdPipeline) -> String {
    let action = pipeline
        .auth
        .action
        .as_deref()
        .unwrap_or("azure/login@v2");

    format!(
        "\
      - name: Azure login (OIDC)
        uses: {action}
        with:
          client-id: ${{{{ secrets.AZURE_CLIENT_ID }}}}
          tenant-id: ${{{{ secrets.AZURE_TENANT_ID }}}}
          subscription-id: ${{{{ secrets.AZURE_SUBSCRIPTION_ID }}}}\n\n",
    )
}

fn render_docker_step(pipeline: &CdPipeline) -> String {
    format!(
        "\
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: {context}
          file: {dockerfile}
          push: true
          tags: {image_tag}
          cache-from: type=gha
          cache-to: type=gha,mode=max\n\n",
        context = pipeline.docker_build_push.context,
        dockerfile = pipeline.docker_build_push.dockerfile,
        image_tag = pipeline.docker_build_push.image_tag,
    )
}

fn render_migration_step(
    migration: &crate::generator::cd_generation::schema::MigrationStep,
) -> String {
    if migration.via_ssh {
        format!(
            "\
      - name: Run database migrations ({tool}) via SSH
        run: |
          ssh ${{{{ secrets.SSH_USER }}}}@${{{{ secrets.SSH_HOST }}}} << 'MIGRATE_EOF'
            cd /opt/app && {command}
          MIGRATE_EOF
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    } else {
        format!(
            "\
      - name: Run database migrations ({tool})
        run: {command}
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    }
}

fn render_deploy_step(pipeline: &CdPipeline) -> String {
    match pipeline.deploy_target {
        DeployTarget::AppService => format!(
            "\
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{{{ secrets.AZURE_APP_NAME }}}}
          images: {image_tag}\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        DeployTarget::Aks => format!(
            "\
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{{{ secrets.AKS_RESOURCE_GROUP }}}}
          cluster-name: ${{{{ secrets.AKS_CLUSTER_NAME }}}}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{{{ secrets.K8S_NAMESPACE }}}}
          images: {image_tag}
          manifests: |
            k8s/\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        DeployTarget::ContainerApps => format!(
            "\
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy@v2
        with:
          containerAppName: ${{{{ secrets.CONTAINER_APP_NAME }}}}
          resourceGroup: ${{{{ secrets.AZURE_RESOURCE_GROUP }}}}
          imageToDeploy: {image_tag}\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        _ => format!(
            "\
      - name: Deploy ({target})
        run: echo 'Deploy step for {target} — customize this step'
        env:
          IMAGE_TAG: {image_tag}\n\n",
            target = pipeline.deploy_target,
            image_tag = pipeline.docker_build_push.image_tag,
        ),
    }
}

fn render_health_check_step(pipeline: &CdPipeline) -> String {
    if is_kubectl_health_check(&pipeline.deploy_target) {
        let timeout = pipeline.health_check.retries * pipeline.health_check.interval_secs;
        format!(
            "\
      - name: Health check — rollout status
        run: |
          kubectl rollout status deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}} \\
            --timeout={timeout}s\n\n",
        )
    } else {
        format!(
            "\
      - name: Health check
        run: |
          curl --fail \\
            --retry {retries} \\
            --retry-delay {interval} \\
            --retry-all-errors \\
            -o /dev/null -s -w '%{{http_code}}' \\
            {url}\n\n",
            retries = pipeline.health_check.retries,
            interval = pipeline.health_check.interval_secs,
            url = pipeline.health_check.url,
        )
    }
}

fn render_rollback_comment(pipeline: &CdPipeline) -> String {
    format!(
        "\
# ── Rollback ──────────────────────────────────────────────────
# Strategy: {strategy}
# Command:  {command}
",
        strategy = pipeline.rollback_info.strategy,
        command = pipeline.rollback_info.command_hint,
    )
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generator::cd_generation::{
        context::{CdPlatform, DeployTarget, MigrationTool, Registry},
        schema::*,
    };

    fn sample_pipeline(target: DeployTarget, with_migration: bool) -> CdPipeline {
        CdPipeline {
            project_name: "my-app".to_string(),
            platform: CdPlatform::Azure,
            deploy_target: target.clone(),
            environments: vec![EnvironmentConfig {
                name: "production".to_string(),
                branch_filter: None,
                requires_approval: true,
                app_url: Some("https://my-app.azurewebsites.net".to_string()),
                namespace: None,
                replicas: None,
            }],
            auth: AuthStep {
                action: Some("azure/login@v2".to_string()),
                method: "oidc".to_string(),
                required_secrets: vec![
                    "AZURE_CLIENT_ID".to_string(),
                    "AZURE_TENANT_ID".to_string(),
                    "AZURE_SUBSCRIPTION_ID".to_string(),
                ],
            },
            registry: RegistryStep {
                registry: Registry::Acr,
                login_action: Some("azure/docker-login@v2".to_string()),
                registry_url: "${{ secrets.ACR_LOGIN_SERVER }}".to_string(),
            },
            docker_build_push: DockerBuildPushStep {
                image_tag: "${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }}".to_string(),
                dockerfile: "Dockerfile".to_string(),
                context: ".".to_string(),
                push: true,
                buildx: true,
                build_args: vec![],
            },
            migration: if with_migration {
                Some(MigrationStep {
                    tool: MigrationTool::Prisma,
                    command: "npx prisma migrate deploy".to_string(),
                    via_ssh: false,
                })
            } else {
                None
            },
            terraform: None,
            deploy: DeployStep {
                target: target.clone(),
                strategy: "rolling".to_string(),
                command: "azure/webapps-deploy@v3".to_string(),
                args: vec![],
            },
            health_check: HealthCheckStep {
                url: "https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net/health".to_string(),
                retries: 5,
                interval_secs: 10,
                expected_status: 200,
            },
            rollback_info: RollbackInfo {
                strategy: "redeploy-previous".to_string(),
                command_hint: "az webapp deployment slot swap".to_string(),
            },
            notifications: None,
            unresolved_tokens: vec![],
            default_branch: "main".to_string(),
            image_name: "my-app".to_string(),
        }
    }

    #[test]
    fn header_contains_project_name() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("my-app"));
    }

    #[test]
    fn header_contains_branch() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("- main"));
    }

    #[test]
    fn header_has_workflow_dispatch() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("workflow_dispatch"));
    }

    #[test]
    fn header_has_oidc_permissions() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("id-token: write"));
    }

    #[test]
    fn contains_checkout() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("actions/checkout@v4"));
    }

    #[test]
    fn contains_azure_login() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("azure/login@v2"));
    }

    #[test]
    fn contains_docker_buildx_setup() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("docker/setup-buildx-action@v3"));
    }

    #[test]
    fn contains_docker_build_push() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("docker/build-push-action@v6"));
    }

    #[test]
    fn contains_health_check() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("Health check"));
    }

    #[test]
    fn contains_rollback_comment() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("Rollback"));
        assert!(yaml.contains("redeploy-previous"));
    }

    #[test]
    fn app_service_deploy_uses_webapps_action() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("azure/webapps-deploy@v3"));
    }

    #[test]
    fn aks_deploy_uses_k8s_deploy_action() {
        let yaml = render(&sample_pipeline(DeployTarget::Aks, false));
        assert!(yaml.contains("azure/k8s-deploy@v5"));
    }

    #[test]
    fn aks_deploy_sets_context() {
        let yaml = render(&sample_pipeline(DeployTarget::Aks, false));
        assert!(yaml.contains("azure/aks-set-context@v4"));
    }

    #[test]
    fn container_apps_deploy_uses_action() {
        let yaml = render(&sample_pipeline(DeployTarget::ContainerApps, false));
        assert!(yaml.contains("azure/container-apps-deploy@v2"));
    }

    #[test]
    fn no_migration_when_absent() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(!yaml.contains("migration"));
    }

    #[test]
    fn migration_present_when_set() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, true));
        assert!(yaml.contains("prisma migrate deploy"));
    }

    #[test]
    fn migration_references_database_url() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, true));
        assert!(yaml.contains("DATABASE_URL"));
    }

    #[test]
    fn app_service_health_check_uses_curl() {
        let yaml = render(&sample_pipeline(DeployTarget::AppService, false));
        assert!(yaml.contains("curl --fail"));
    }

    #[test]
    fn aks_health_check_uses_kubectl() {
        let yaml = render(&sample_pipeline(DeployTarget::Aks, false));
        assert!(yaml.contains("kubectl rollout status"));
    }

    #[test]
    fn filename_is_deploy_azure() {
        assert_eq!(workflow_filename(), "deploy-azure.yml");
    }
}
