//! CD-19 — GCP CD Template Builder
//!
//! Assembles a complete `.github/workflows/deploy-gcp.yml` from a
//! `CdPipeline` struct. The pipeline order is:
//!
//! 1. Checkout
//! 2. GCP auth (Workload Identity Federation)
//! 3. Configure Docker for GAR
//! 4. Docker build + push (via Buildx)
//! 5. Database migration *(optional)*
//! 6. Deploy to target (Cloud Run / GKE)
//! 7. Health check
//!
//! Like the Azure template, all YAML is assembled directly from `CdPipeline`
//! schema types via string formatting.

use crate::generator::cd_generation::{
    context::DeployTarget,
    health_check::is_kubectl_health_check,
    schema::CdPipeline,
};

/// Renders a complete GCP CD workflow YAML string.
pub fn render(pipeline: &CdPipeline) -> String {
    let mut yaml = String::with_capacity(4096);

    yaml.push_str(&render_header(pipeline));
    yaml.push_str("jobs:\n");
    yaml.push_str("  deploy:\n");
    yaml.push_str("    runs-on: ubuntu-latest\n");
    yaml.push_str("    steps:\n");

    // 1. Checkout
    yaml.push_str("      - uses: actions/checkout@v4\n\n");

    // 2. GCP auth (WIF)
    yaml.push_str(&render_auth_step(pipeline));

    // 3. Configure Docker for GAR
    yaml.push_str(&render_gar_docker_auth());

    // 4. Docker build + push
    yaml.push_str(&render_docker_step(pipeline));

    // 5. Migration (optional)
    if let Some(ref migration) = pipeline.migration {
        yaml.push_str(&render_migration_step(migration));
    }

    // 6. Deploy
    yaml.push_str(&render_deploy_step(pipeline));

    // 7. Health check
    yaml.push_str(&render_health_check_step(pipeline));

    // Rollback comment
    yaml.push_str(&render_rollback_comment(pipeline));

    yaml
}

/// Returns the canonical output filename.
pub fn workflow_filename() -> &'static str {
    "deploy-gcp.yml"
}

// ── Private renderers ─────────────────────────────────────────────────────────

fn render_header(pipeline: &CdPipeline) -> String {
    format!(
        "\
# Auto-generated by sync-ctl — GCP CD pipeline for {project}
# Target: {target}
name: Deploy to GCP ({target})

on:
  push:
    branches:
      - {branch}
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: {image}

",
        project = pipeline.project_name,
        target = pipeline.deploy_target,
        branch = pipeline.default_branch,
        image = pipeline.image_name,
    )
}

fn render_auth_step(pipeline: &CdPipeline) -> String {
    let action = pipeline
        .auth
        .action
        .as_deref()
        .unwrap_or("google-github-actions/auth@v2");

    format!(
        "\
      - name: Authenticate to Google Cloud
        id: auth
        uses: {action}
        with:
          workload_identity_provider: ${{{{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}}}
          service_account: ${{{{ secrets.GCP_SERVICE_ACCOUNT }}}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2\n\n",
    )
}

fn render_gar_docker_auth() -> String {
    "\
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev --quiet\n\n"
        .to_string()
}

fn render_docker_step(pipeline: &CdPipeline) -> String {
    format!(
        "\
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: {context}
          file: {dockerfile}
          push: true
          tags: {image_tag}
          cache-from: type=gha
          cache-to: type=gha,mode=max\n\n",
        context = pipeline.docker_build_push.context,
        dockerfile = pipeline.docker_build_push.dockerfile,
        image_tag = pipeline.docker_build_push.image_tag,
    )
}

fn render_migration_step(
    migration: &crate::generator::cd_generation::schema::MigrationStep,
) -> String {
    if migration.via_ssh {
        format!(
            "\
      - name: Run database migrations ({tool}) via SSH
        run: |
          ssh ${{{{ secrets.SSH_USER }}}}@${{{{ secrets.SSH_HOST }}}} << 'MIGRATE_EOF'
            cd /opt/app && {command}
          MIGRATE_EOF
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    } else {
        format!(
            "\
      - name: Run database migrations ({tool})
        run: {command}
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    }
}

fn render_deploy_step(pipeline: &CdPipeline) -> String {
    match pipeline.deploy_target {
        DeployTarget::CloudRun => format!(
            "\
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{{{ secrets.CLOUD_RUN_SERVICE }}}}
          region: ${{{{ secrets.GCP_REGION }}}}
          image: {image_tag}\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        DeployTarget::Gke => format!(
            "\
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{{{ secrets.GKE_CLUSTER_NAME }}}}
          location: ${{{{ secrets.GKE_LOCATION }}}}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            ${{{{ secrets.K8S_DEPLOYMENT_NAME }}}}={image_tag} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}}
          kubectl rollout status deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}} \\
            --timeout=300s\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        _ => format!(
            "\
      - name: Deploy ({target})
        run: echo 'Deploy step for {target} — customize this step'
        env:
          IMAGE_TAG: {image_tag}\n\n",
            target = pipeline.deploy_target,
            image_tag = pipeline.docker_build_push.image_tag,
        ),
    }
}

fn render_health_check_step(pipeline: &CdPipeline) -> String {
    if is_kubectl_health_check(&pipeline.deploy_target) {
        let timeout = pipeline.health_check.retries * pipeline.health_check.interval_secs;
        format!(
            "\
      - name: Health check — rollout status
        run: |
          kubectl rollout status deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}} \\
            --timeout={timeout}s\n\n",
        )
    } else if matches!(pipeline.deploy_target, DeployTarget::CloudRun) {
        format!(
            "\
      - name: Health check
        run: |
          curl --fail \\
            --retry {retries} \\
            --retry-delay {interval} \\
            --retry-all-errors \\
            -o /dev/null -s -w '%{{http_code}}' \\
            ${{{{ steps.deploy.outputs.url }}}}/health\n\n",
            retries = pipeline.health_check.retries,
            interval = pipeline.health_check.interval_secs,
        )
    } else {
        format!(
            "\
      - name: Health check
        run: |
          curl --fail \\
            --retry {retries} \\
            --retry-delay {interval} \\
            --retry-all-errors \\
            -o /dev/null -s -w '%{{http_code}}' \\
            {url}\n\n",
            retries = pipeline.health_check.retries,
            interval = pipeline.health_check.interval_secs,
            url = pipeline.health_check.url,
        )
    }
}

fn render_rollback_comment(pipeline: &CdPipeline) -> String {
    format!(
        "\
# ── Rollback ──────────────────────────────────────────────────
# Strategy: {strategy}
# Command:  {command}
",
        strategy = pipeline.rollback_info.strategy,
        command = pipeline.rollback_info.command_hint,
    )
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generator::cd_generation::{
        context::{CdPlatform, DeployTarget, MigrationTool, Registry},
        schema::*,
    };

    fn sample_gcp_pipeline(target: DeployTarget, with_migration: bool) -> CdPipeline {
        CdPipeline {
            project_name: "my-api".to_string(),
            platform: CdPlatform::Gcp,
            deploy_target: target.clone(),
            environments: vec![EnvironmentConfig {
                name: "production".to_string(),
                branch_filter: None,
                requires_approval: true,
                app_url: None,
                namespace: None,
                replicas: None,
            }],
            auth: AuthStep {
                action: Some("google-github-actions/auth@v2".to_string()),
                method: "workload-identity".to_string(),
                required_secrets: vec![
                    "GCP_WORKLOAD_IDENTITY_PROVIDER".to_string(),
                    "GCP_SERVICE_ACCOUNT".to_string(),
                ],
            },
            registry: RegistryStep {
                registry: Registry::Gar,
                login_action: Some("docker/login-action@v3".to_string()),
                registry_url: "${{ secrets.GAR_LOCATION }}-docker.pkg.dev".to_string(),
            },
            docker_build_push: DockerBuildPushStep {
                image_tag: "${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-api:${{ github.sha }}".to_string(),
                dockerfile: "Dockerfile".to_string(),
                context: ".".to_string(),
                push: true,
                buildx: true,
                build_args: vec![],
            },
            migration: if with_migration {
                Some(MigrationStep {
                    tool: MigrationTool::Alembic,
                    command: "alembic upgrade head".to_string(),
                    via_ssh: false,
                })
            } else {
                None
            },
            terraform: None,
            deploy: DeployStep {
                target: target.clone(),
                strategy: "rolling".to_string(),
                command: "google-github-actions/deploy-cloudrun@v2".to_string(),
                args: vec![],
            },
            health_check: HealthCheckStep {
                url: "${{ steps.deploy.outputs.url }}/health".to_string(),
                retries: 5,
                interval_secs: 10,
                expected_status: 200,
            },
            rollback_info: RollbackInfo {
                strategy: "traffic-shift".to_string(),
                command_hint: "gcloud run services update-traffic --to-revisions=LATEST=0".to_string(),
            },
            notifications: None,
            unresolved_tokens: vec![],
            default_branch: "main".to_string(),
            image_name: "my-api".to_string(),
        }
    }

    // ── Header ────────────────────────────────────────────────────────

    #[test]
    fn header_contains_project_name() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("my-api"));
    }

    #[test]
    fn header_has_oidc_permissions() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("id-token: write"));
    }

    #[test]
    fn header_has_workflow_dispatch() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("workflow_dispatch"));
    }

    // ── Structure ─────────────────────────────────────────────────────

    #[test]
    fn contains_checkout() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("actions/checkout@v4"));
    }

    #[test]
    fn contains_gcp_auth() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("google-github-actions/auth@v2"));
    }

    #[test]
    fn contains_setup_gcloud() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("google-github-actions/setup-gcloud@v2"));
    }

    #[test]
    fn contains_gar_docker_auth() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("gcloud auth configure-docker"));
    }

    #[test]
    fn contains_docker_buildx() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("docker/setup-buildx-action@v3"));
    }

    #[test]
    fn contains_docker_build_push() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("docker/build-push-action@v6"));
    }

    // ── Cloud Run deploy ──────────────────────────────────────────────

    #[test]
    fn cloud_run_deploy_uses_action() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("google-github-actions/deploy-cloudrun@v2"));
    }

    #[test]
    fn cloud_run_health_check_uses_step_output() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("steps.deploy.outputs.url"));
    }

    // ── GKE deploy ────────────────────────────────────────────────────

    #[test]
    fn gke_deploy_uses_get_credentials() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::Gke, false));
        assert!(yaml.contains("google-github-actions/get-gke-credentials@v2"));
    }

    #[test]
    fn gke_deploy_uses_kubectl() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::Gke, false));
        assert!(yaml.contains("kubectl set image"));
    }

    #[test]
    fn gke_deploy_has_rollout_status() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::Gke, false));
        assert!(yaml.contains("kubectl rollout status"));
    }

    // ── Migration ─────────────────────────────────────────────────────

    #[test]
    fn no_migration_when_absent() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(!yaml.contains("migration"));
    }

    #[test]
    fn migration_present_when_set() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, true));
        assert!(yaml.contains("alembic upgrade head"));
    }

    // ── Rollback ──────────────────────────────────────────────────────

    #[test]
    fn rollback_comment_present() {
        let yaml = render(&sample_gcp_pipeline(DeployTarget::CloudRun, false));
        assert!(yaml.contains("Rollback"));
        assert!(yaml.contains("traffic-shift"));
    }

    // ── Filename ──────────────────────────────────────────────────────

    #[test]
    fn filename_is_deploy_gcp() {
        assert_eq!(workflow_filename(), "deploy-gcp.yml");
    }
}
