//! CD-20 — Hetzner CD Template Builder
//!
//! Assembles a complete `.github/workflows/deploy-hetzner.yml` from a
//! `CdPipeline` struct. The pipeline order is:
//!
//! 1. Checkout
//! 2. GHCR login
//! 3. Docker build + push (via Buildx)
//! 4. SSH agent setup *(VPS / Coolify)*
//! 5. Database migration via SSH *(optional)*
//! 6. Deploy to target (VPS / HetznerK8s / Coolify)
//! 7. Health check
//!
//! Hetzner targets are unique because VPS and Coolify deploy over SSH,
//! while HetznerK8s uses a kubeconfig secret. The template builder
//! adapts the steps accordingly.

use crate::generator::cd_generation::{
    context::DeployTarget,
    health_check::is_kubectl_health_check,
    schema::CdPipeline,
};

/// Renders a complete Hetzner CD workflow YAML string.
pub fn render(pipeline: &CdPipeline) -> String {
    let mut yaml = String::with_capacity(4096);

    yaml.push_str(&render_header(pipeline));
    yaml.push_str("jobs:\n");
    yaml.push_str("  deploy:\n");
    yaml.push_str("    runs-on: ubuntu-latest\n");
    yaml.push_str("    steps:\n");

    // 1. Checkout
    yaml.push_str("      - uses: actions/checkout@v4\n\n");

    // 2. GHCR login
    yaml.push_str(&render_ghcr_login());

    // 3. Docker build + push
    yaml.push_str(&render_docker_step(pipeline));

    // 4. SSH agent (for VPS and Coolify targets)
    if needs_ssh(&pipeline.deploy_target) {
        yaml.push_str(&render_ssh_agent());
    }

    // 4b. Kubeconfig (for HetznerK8s)
    if matches!(pipeline.deploy_target, DeployTarget::HetznerK8s) {
        yaml.push_str(&render_kubeconfig());
    }

    // 5. Migration (optional)
    if let Some(ref migration) = pipeline.migration {
        yaml.push_str(&render_migration_step(migration));
    }

    // 6. Deploy
    yaml.push_str(&render_deploy_step(pipeline));

    // 7. Health check
    yaml.push_str(&render_health_check_step(pipeline));

    // Rollback comment
    yaml.push_str(&render_rollback_comment(pipeline));

    yaml
}

/// Returns the canonical output filename.
pub fn workflow_filename() -> &'static str {
    "deploy-hetzner.yml"
}

/// Returns `true` if the target requires SSH agent setup.
fn needs_ssh(target: &DeployTarget) -> bool {
    matches!(target, DeployTarget::Vps | DeployTarget::Coolify)
}

// ── Private renderers ─────────────────────────────────────────────────────────

fn render_header(pipeline: &CdPipeline) -> String {
    format!(
        "\
# Auto-generated by sync-ctl — Hetzner CD pipeline for {project}
# Target: {target}
name: Deploy to Hetzner ({target})

on:
  push:
    branches:
      - {branch}
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: {image}

",
        project = pipeline.project_name,
        target = pipeline.deploy_target,
        branch = pipeline.default_branch,
        image = pipeline.image_name,
    )
}

fn render_ghcr_login() -> String {
    "      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}\n\n"
        .to_string()
}

fn render_docker_step(pipeline: &CdPipeline) -> String {
    format!(
        "      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: {context}
          file: {dockerfile}
          push: true
          tags: {image_tag}
          cache-from: type=gha
          cache-to: type=gha,mode=max\n\n",
        context = pipeline.docker_build_push.context,
        dockerfile = pipeline.docker_build_push.dockerfile,
        image_tag = pipeline.docker_build_push.image_tag,
    )
}

fn render_ssh_agent() -> String {
    "      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}\n\n"
        .to_string()
}

fn render_kubeconfig() -> String {
    "      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo \"${{ secrets.KUBECONFIG }}\" > ~/.kube/config
          chmod 600 ~/.kube/config\n\n"
        .to_string()
}

fn render_migration_step(
    migration: &crate::generator::cd_generation::schema::MigrationStep,
) -> String {
    if migration.via_ssh {
        format!(
            "      - name: Run database migrations ({tool}) via SSH
        run: |
          ssh ${{{{ secrets.SSH_USER }}}}@${{{{ secrets.SSH_HOST }}}} << 'MIGRATE_EOF'
            cd /opt/app && {command}
          MIGRATE_EOF
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    } else {
        format!(
            "      - name: Run database migrations ({tool})
        run: {command}
        env:
          DATABASE_URL: ${{{{ secrets.DATABASE_URL }}}}\n\n",
            tool = migration.tool,
            command = migration.command,
        )
    }
}

fn render_deploy_step(pipeline: &CdPipeline) -> String {
    match pipeline.deploy_target {
        DeployTarget::Vps => format!(
            "      - name: Deploy to VPS via SSH
        run: |
          ssh ${{{{ secrets.SSH_USER }}}}@${{{{ secrets.SSH_HOST }}}} << 'DEPLOY_EOF'
            docker pull {image_tag}
            cd /opt/app && docker compose up -d
          DEPLOY_EOF\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        DeployTarget::HetznerK8s => format!(
            "      - name: Deploy to Hetzner Kubernetes
        run: |
          kubectl set image deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            ${{{{ secrets.K8S_DEPLOYMENT_NAME }}}}={image_tag} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}}
          kubectl rollout status deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}} \\
            --timeout=300s\n\n",
            image_tag = pipeline.docker_build_push.image_tag,
        ),
        DeployTarget::Coolify => "      - name: Deploy via Coolify webhook
        run: |
          curl -fsSL -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }}\n\n"
            .to_string(),
        _ => format!(
            "      - name: Deploy ({target})
        run: echo 'Deploy step for {target} — customize this step'
        env:
          IMAGE_TAG: {image_tag}\n\n",
            target = pipeline.deploy_target,
            image_tag = pipeline.docker_build_push.image_tag,
        ),
    }
}

fn render_health_check_step(pipeline: &CdPipeline) -> String {
    if is_kubectl_health_check(&pipeline.deploy_target) {
        let timeout = pipeline.health_check.retries * pipeline.health_check.interval_secs;
        format!(
            "      - name: Health check — rollout status
        run: |
          kubectl rollout status deployment/${{{{ secrets.K8S_DEPLOYMENT_NAME }}}} \\
            --namespace=${{{{ secrets.K8S_NAMESPACE }}}} \\
            --timeout={timeout}s\n\n",
        )
    } else {
        format!(
            "      - name: Health check
        run: |
          curl --fail \\
            --retry {retries} \\
            --retry-delay {interval} \\
            --retry-all-errors \\
            -o /dev/null -s -w '%{{http_code}}' \\
            {url}\n\n",
            retries = pipeline.health_check.retries,
            interval = pipeline.health_check.interval_secs,
            url = pipeline.health_check.url,
        )
    }
}

fn render_rollback_comment(pipeline: &CdPipeline) -> String {
    format!(
        "\
# ── Rollback ──────────────────────────────────────────────────
# Strategy: {strategy}
# Command:  {command}
",
        strategy = pipeline.rollback_info.strategy,
        command = pipeline.rollback_info.command_hint,
    )
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generator::cd_generation::{
        context::{CdPlatform, DeployTarget, MigrationTool, Registry},
        schema::*,
    };

    fn sample_hetzner_pipeline(target: DeployTarget, with_migration: bool) -> CdPipeline {
        let via_ssh = matches!(target, DeployTarget::Vps);
        CdPipeline {
            project_name: "my-svc".to_string(),
            platform: CdPlatform::Hetzner,
            deploy_target: target.clone(),
            environments: vec![EnvironmentConfig {
                name: "production".to_string(),
                branch_filter: None,
                requires_approval: false,
                app_url: None,
                namespace: None,
                replicas: None,
            }],
            auth: AuthStep {
                action: None,
                method: "ssh".to_string(),
                required_secrets: vec!["SSH_PRIVATE_KEY".to_string()],
            },
            registry: RegistryStep {
                registry: Registry::Ghcr,
                login_action: Some("docker/login-action@v3".to_string()),
                registry_url: "ghcr.io".to_string(),
            },
            docker_build_push: DockerBuildPushStep {
                image_tag: "ghcr.io/${{ github.repository_owner }}/my-svc:${{ github.sha }}"
                    .to_string(),
                dockerfile: "Dockerfile".to_string(),
                context: ".".to_string(),
                push: true,
                buildx: true,
                build_args: vec![],
            },
            migration: if with_migration {
                Some(MigrationStep {
                    tool: MigrationTool::Diesel,
                    command: "diesel migration run".to_string(),
                    via_ssh,
                })
            } else {
                None
            },
            terraform: None,
            deploy: DeployStep {
                target: target.clone(),
                strategy: "recreate".to_string(),
                command: "ssh".to_string(),
                args: vec![],
            },
            health_check: HealthCheckStep {
                url: "https://${{ secrets.SSH_HOST }}/health".to_string(),
                retries: 5,
                interval_secs: 10,
                expected_status: 200,
            },
            rollback_info: RollbackInfo {
                strategy: "manual".to_string(),
                command_hint: "ssh user@host 'docker compose up -d --force-recreate'".to_string(),
            },
            notifications: None,
            unresolved_tokens: vec![],
            default_branch: "main".to_string(),
            image_name: "my-svc".to_string(),
        }
    }

    // ── Header ────────────────────────────────────────────────────────

    #[test]
    fn header_contains_project_name() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("my-svc"));
    }

    #[test]
    fn header_has_packages_write_permission() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("packages: write"));
    }

    #[test]
    fn header_has_workflow_dispatch() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("workflow_dispatch"));
    }

    // ── Structure ─────────────────────────────────────────────────────

    #[test]
    fn contains_checkout() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("actions/checkout@v4"));
    }

    #[test]
    fn contains_ghcr_login() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("docker/login-action@v3"));
        assert!(yaml.contains("ghcr.io"));
    }

    #[test]
    fn contains_docker_buildx() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("docker/setup-buildx-action@v3"));
    }

    // ── SSH agent ─────────────────────────────────────────────────────

    #[test]
    fn vps_has_ssh_agent() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("webfactory/ssh-agent@v0.9.0"));
    }

    #[test]
    fn coolify_has_ssh_agent() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Coolify, false));
        assert!(yaml.contains("webfactory/ssh-agent@v0.9.0"));
    }

    #[test]
    fn k8s_has_no_ssh_agent() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::HetznerK8s, false));
        assert!(!yaml.contains("ssh-agent"));
    }

    #[test]
    fn k8s_has_kubeconfig() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::HetznerK8s, false));
        assert!(yaml.contains("KUBECONFIG"));
    }

    // ── VPS deploy ────────────────────────────────────────────────────

    #[test]
    fn vps_deploy_uses_ssh() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("ssh ${{ secrets.SSH_USER }}"));
    }

    #[test]
    fn vps_deploy_pulls_image() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("docker pull"));
    }

    #[test]
    fn vps_deploy_composes_up() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("docker compose up -d"));
    }

    // ── HetznerK8s deploy ─────────────────────────────────────────────

    #[test]
    fn k8s_deploy_uses_kubectl() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::HetznerK8s, false));
        assert!(yaml.contains("kubectl set image"));
    }

    #[test]
    fn k8s_deploy_has_rollout_status() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::HetznerK8s, false));
        assert!(yaml.contains("kubectl rollout status"));
    }

    // ── Coolify deploy ────────────────────────────────────────────────

    #[test]
    fn coolify_deploy_uses_webhook() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Coolify, false));
        assert!(yaml.contains("COOLIFY_WEBHOOK_URL"));
    }

    // ── Migration ─────────────────────────────────────────────────────

    #[test]
    fn no_migration_when_absent() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(!yaml.contains("migration"));
    }

    #[test]
    fn migration_via_ssh_for_vps() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, true));
        assert!(yaml.contains("diesel migration run"));
        assert!(yaml.contains("via SSH"));
    }

    // ── Health check ──────────────────────────────────────────────────

    #[test]
    fn vps_health_check_uses_curl() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("curl --fail"));
    }

    #[test]
    fn k8s_health_check_uses_kubectl() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::HetznerK8s, false));
        assert!(yaml.contains("kubectl rollout status"));
    }

    // ── Rollback ──────────────────────────────────────────────────────

    #[test]
    fn rollback_comment_present() {
        let yaml = render(&sample_hetzner_pipeline(DeployTarget::Vps, false));
        assert!(yaml.contains("Rollback"));
        assert!(yaml.contains("manual"));
    }

    // ── Filename ──────────────────────────────────────────────────────

    #[test]
    fn filename_is_deploy_hetzner() {
        assert_eq!(workflow_filename(), "deploy-hetzner.yml");
    }
}
