use crate::{analyzer::analyze_monorepo, generator};

pub fn handle_generate(
    path: std::path::PathBuf,
    _output: Option<std::path::PathBuf>,
    dockerfile: bool,
    compose: bool,
    terraform: bool,
    all: bool,
    dry_run: bool,
    _force: bool,
) -> crate::Result<()> {
    println!("🔍 Analyzing project for generation: {}", path.display());

    let monorepo_analysis = analyze_monorepo(&path)?;

    println!("✅ Analysis complete. Generating IaC files...");

    if monorepo_analysis.is_monorepo {
        println!(
            "📦 Detected monorepo with {} projects",
            monorepo_analysis.projects.len()
        );
        println!(
            "🚧 Monorepo IaC generation is coming soon! For now, generating for the overall structure."
        );
        println!(
            "💡 Tip: You can run generate commands on individual project directories for now."
        );
    }

    // For now, use the first/main project for generation
    // TODO: Implement proper monorepo IaC generation
    let main_project = &monorepo_analysis.projects[0];

    let generate_all = all || (!dockerfile && !compose && !terraform);

    if generate_all || dockerfile {
        println!("\n🐳 Generating Dockerfile...");
        let dockerfile_content = generator::generate_dockerfile(&main_project.analysis)?;

        if dry_run {
            println!("--- Dockerfile (dry run) ---");
            println!("{}", dockerfile_content);
        } else {
            std::fs::write("Dockerfile", dockerfile_content)?;
            println!("✅ Dockerfile generated successfully!");
        }
    }

    if generate_all || compose {
        println!("\n🐙 Generating Docker Compose file...");
        let compose_content = generator::generate_compose(&main_project.analysis)?;

        if dry_run {
            println!("--- docker-compose.yml (dry run) ---");
            println!("{}", compose_content);
        } else {
            std::fs::write("docker-compose.yml", compose_content)?;
            println!("✅ Docker Compose file generated successfully!");
        }
    }

    if generate_all || terraform {
        println!("\n🏗️  Generating Terraform configuration...");
        let terraform_content = generator::generate_terraform(&main_project.analysis)?;

        if dry_run {
            println!("--- main.tf (dry run) ---");
            println!("{}", terraform_content);
        } else {
            std::fs::write("main.tf", terraform_content)?;
            println!("✅ Terraform configuration generated successfully!");
        }
    }

    if !dry_run {
        println!("\n🎉 Generation complete! IaC files have been created in the current directory.");

        if monorepo_analysis.is_monorepo {
            println!("🔧 Note: Generated files are based on the main project structure.");
            println!("   Advanced monorepo support with per-project generation is coming soon!");
        }
    }

    Ok(())
}

pub fn handle_validate(
    _path: std::path::PathBuf,
    _types: Option<Vec<String>>,
    _fix: bool,
) -> crate::Result<()> {
    println!("🔍 Validating IaC files...");
    println!("⚠️  Validation feature is not yet implemented.");
    Ok(())
}

/// CI-01: entry-point stub for `sync-ctl generate ci`.
///
/// Produces a minimal but syntactically valid pipeline skeleton so that the
/// acceptance criterion (`--dry-run` prints valid YAML) is satisfied at the
/// CLI layer. Full template rendering (CI-11/12/13) replaces this output once
/// the context and schema layers (CI-02, CI-14) are implemented.
pub fn handle_generate_ci(
    path: std::path::PathBuf,
    platform: crate::cli::CiPlatform,
    format: Option<crate::cli::CiFormat>,
    dry_run: bool,
    output: Option<std::path::PathBuf>,
    env_prefix: Option<String>,
    skip_docker: bool,
) -> crate::Result<()> {
    use crate::cli::{CiFormat, CiPlatform};

    // Resolve the effective format: use the caller's choice when given, otherwise
    // pick the canonical default for the chosen platform.
    let effective_format = format.unwrap_or(match platform {
        CiPlatform::Azure => CiFormat::AzurePipelines,
        CiPlatform::Gcp => CiFormat::CloudBuild,
        CiPlatform::Hetzner => CiFormat::GithubActions,
    });

    let prefix = env_prefix.as_deref().unwrap_or("APP");

    // Build a minimal valid YAML skeleton per format.  All values that cannot
    // be resolved without project analysis become {{PLACEHOLDER}} tokens.
    // CI-02 through CI-14 will replace this with a fully rendered CiPipeline.
    let skeleton = match effective_format {
        CiFormat::GithubActions => format!(
            r#"# Generated by sync-ctl generate ci (skeleton — CI-02+ fills placeholders)
# Project path : {path}
# Platform     : {platform_label}
# Env prefix   : {prefix}
# Skip docker  : {skip_docker}
name: CI
on:
  push:
    branches: ["{{{{DEFAULT_BRANCH}}}}", develop]
  pull_request:
    branches: ["{{{{DEFAULT_BRANCH}}}}"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # CI-03: setup-runtime
      - uses: "{{{{SETUP_ACTION}}}}"
        with:
          "{{{{RUNTIME_KEY}}}}": "{{{{RUNTIME_VERSION}}}}"

      # CI-04: cache-deps
      - uses: actions/cache@v4
        with:
          path: "{{{{CACHE_PATH}}}}"
          key: "${{{{ runner.os }}}}-deps-${{{{ hashFiles('{{{{LOCK_FILE}}}}') }}}}"

      # CI-04: install
      - name: Install dependencies
        run: "{{{{INSTALL_COMMAND}}}}"

      # CI-06: lint (omitted if no linter detected)
      # - name: Lint
      #   run: {{{{LINT_COMMAND}}}}

      # CI-05: test
      - name: Test
        run: "{{{{TEST_COMMAND}}}}"

      # CI-07: build
      - name: Build
        run: "{{{{BUILD_COMMAND}}}}"
{docker_block}
      # CI-10: secret scan
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: "${{{{ secrets.GITHUB_TOKEN }}}}"
"#,
            path = path.display(),
            platform_label = "GitHub Actions",
            prefix = prefix,
            skip_docker = skip_docker,
            docker_block = if skip_docker {
                String::new()
            } else {
                format!(
                    r#"
      # CI-08: docker build (omitted if --skip-docker or no Dockerfile detected)
      - name: Build Docker image
        run: docker build -t "${{{{ secrets.{prefix}_REGISTRY_URL }}}}/{{{{IMAGE_NAME}}}}:${{{{ github.sha }}}}" .
"#
                )
            },
        ),

        CiFormat::AzurePipelines => format!(
            r#"# Generated by sync-ctl generate ci (skeleton — CI-02+ fills placeholders)
# Project path : {path}
# Platform     : Azure Pipelines
# Env prefix   : {prefix}
trigger:
  branches:
    include:
      - "{{{{DEFAULT_BRANCH}}}}"
      - develop
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self

  # CI-03: setup-runtime
  - task: "{{{{AZURE_SETUP_TASK}}}}"
    inputs:
      versionSpec: "{{{{RUNTIME_VERSION}}}}"

  # CI-04: cache-deps
  - task: Cache@2
    inputs:
      key: '"deps" | "$(Agent.OS)" | "{{{{LOCK_FILE}}}}"'
      path: "{{{{CACHE_PATH}}}}"

  # CI-04: install
  - script: "{{{{INSTALL_COMMAND}}}}"
    displayName: Install dependencies

  # CI-05: test
  - script: "{{{{TEST_COMMAND}}}}"
    displayName: Run tests

  # CI-07: build
  - script: "{{{{BUILD_COMMAND}}}}"
    displayName: Build

  # CI-09/10: scanning steps added by CI-09/CI-10
"#,
            path = path.display(),
            prefix = prefix,
        ),

        CiFormat::CloudBuild => format!(
            r#"# Generated by sync-ctl generate ci (skeleton — CI-02+ fills placeholders)
# Project path : {path}
# Platform     : Google Cloud Build
# Env prefix   : {prefix}
steps:
  # CI-04: install
  - name: "{{{{BUILDER_IMAGE}}}}"
    entrypoint: "{{{{PACKAGE_MANAGER}}}}"
    args: ["{{{{INSTALL_ARGS}}}}"]

  # CI-05: test
  - name: "{{{{BUILDER_IMAGE}}}}"
    entrypoint: sh
    args:
      - "-c"
      - "{{{{TEST_COMMAND}}}}"

  # CI-07: build
  - name: "{{{{BUILDER_IMAGE}}}}"
    entrypoint: sh
    args:
      - "-c"
      - "{{{{BUILD_COMMAND}}}}"
{gcp_docker_block}
options:
  logging: CLOUD_LOGGING_ONLY
"#,
            path = path.display(),
            prefix = prefix,
            gcp_docker_block = if skip_docker {
                String::new()
            } else {
                r#"
  # CI-08: docker build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "{{REGISTRY_URL}}/{{IMAGE_NAME}}:$SHORT_SHA"
      - "."
"#
                .to_string()
            },
        ),
    };

    if dry_run {
        println!("{}", skeleton);
    } else {
        // Full file writing arrives in CI-20 (writer.rs).  Until then, inform
        // the user that non-dry-run mode requires CI-20 to be implemented.
        let out_dir = output
            .as_ref()
            .map(|p| p.display().to_string())
            .unwrap_or_else(|| ".".to_string());
        println!("🔧 CI pipeline skeleton ready (platform: {:?})", platform);
        println!("   Would write to: {}", out_dir);
        println!(
            "⚠️  File writing (CI-20) not yet implemented — use --dry-run to preview the skeleton."
        );
    }

    Ok(())
}
